### ISSUE TITLE
Can one use Netbox inventory plugin with Nornir?

### ISSUE THREAD

**Issue by wdennis** [writememe/net-api#28]
Took a look at this project, is interesting as I'm using Nornir to do network automation, and want to progress to front-ending it. However, taking a look at `net.py`, it looks like the `get_nr()` function only allows Nornir "simple inventory"... As I already have all my network devices in Netbox, and that has an inventory plugin for Nornir, is using Netbox inventory a possibility with this project?

**Comment by writememe** [comment]
Hi @wdennis, 

It's technically possible. All that function needs to return is the nr object. You could write a second function named `get_nb_nr()` and make sure it returns the object in the similar way.

I haven't used the netbox inventory plugin before, so perhaps you could share some code or an example?

**Comment by writememe** [comment]
Hi @wdennis,

Just following up on whether you wanted to share some code so I can take a look?

**Comment by wdennis** [comment]
@writememe Sorry for late reply, been busy + holiday time here...
\</excuse\>

Example of my InitNornir invocation and the associated config file:
```
nr = InitNornir(
    config_file="config_nb_network_switches.yaml",
    dry_run=False,
)
nr.inventory.defaults.username = "superuser"
nr.inventory.defaults.password = "5uper53cre7"
```

config_nb_network_switches.yaml:
```
---
core:
    num_workers: 20
inventory:
    plugin: nornir.plugins.inventory.netbox.NBInventory
    options:
        nb_url: "http://netbox.mycompany.com"
        nb_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        use_slugs: True
        flatten_custom_fields: True
        filter_parameters:
            'role': ["core-switch", "distribution-switch", "access-switch", "transit-switch", "management-switch"]
```
This against Nornir 2.4.0; please note that the impending Nornir 3.0.0 will change things in regards to both the way plugins works, as well as the Netbox inventory plugin itself -- see:
- https://github.com/nornir-automation/nornir/issues/486
- https://nornir.readthedocs.io/en/3.0.0/upgrading/2_to_3.html
- https://github.com/wvandeun/nornir_netbox/blob/develop/README.md (see NetBoxInventory2 note)
